spring:
  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址
    host: 192.168.80.100
    # Redis服务器连接端口
    port: 6379
    #Redis服务器连接密码（默认为空）
    password:
    #连接池
    pool:
      #最大连接数（使用负值表示没有限制）
      max-active: 3000
      #连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: 10000
      #最大空闲连接
      max-idle: 1000
      #最小空闲连接
      min-idle: 1000
    #连接超时时间（毫秒）
    timeout: 50000
server:
  context-path: /redis-demo